server:
  port: 8084


spring:
  application:
      name: geteway-service-web
  mvc:
    favicon:
      enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
#        - id: forward-test
#          uri: http://10.26.27.201:9090
#          predicates:
#          - Path=/**
#          order: -10


#      - id: path_route
#        uri: lb://pay-service
#        predicates:
#        - Path=/**
#        - ReadBodyPredicateFactory=Object.class,myPre
#        order: -1
#        filters:
#          ModifyRequestBody=
#
      - id: pay-service
        uri: lb://user-service
        predicates:
        - Path=/user-service/*
        filters:
          - name: ModifyResponseBody
            args:
             in-class: java.lang.String
             out-class: java.lang.String
             rewrite-function: com.aisino.gateway.define.ResponseBodyRewriteFunction



eureka:
  client:
    service-url:
     defaultZone: http://10.26.27.201:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true




logging:
  level:
    root: info





